# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Erfan Farhadi
title: Writer, Programmer, Designer
email: farhadi.erfan76@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  farhadi-erfan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
#facebook_username: jekyll
# flickr_username: jekyll
instagram_username: farhadi.erfan
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Vimeo
  icon: fab fa-vimeo
  url: https://vimeo.com/user114492824
- title: telegram channel
  icon: fab fa-telegram
  url: https://t.me/La_Veillee
- title: CV
  icon: fab fa-dochub
  url: https://drive.google.com/file/d/15xWyLMWC3yI37ysMUL-zTZfWd6nGAVyV/view?usp=share_link

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/photo_2023-01-03_19-46-23.jpg
about_content: | # this will include new lines to allow paragraphs
  For as long as I remember, I liked creating things. Whether it was a computer game when I was ten, a projection tool to display screens on water vapor when I was in junior high, or an hour-long feature film in high school, I enjoyed making them all.
  I studied Computer Engineering at the <mark>Sharif University of Technology</mark> with the goal of acquiring the skills needed for building impactful software. Also, I pursued numerous extracurricular activities like:
    - Contributing to <a href="ssc.ce.sharif.edu">SSC</a>, students' scientific chapter of computer engineering department as a central council member
    - Co-Founding an educational NGO, <a href="rastaiha.ir">Rasta</a>, writing its manifest, creating/presenting workshops at events, and managing its media and technical sections
    - Teaching different courses ranging from calculus and programming to creative writing at Iran's <a href="https://en.wikipedia.org/wiki/National_Organization_for_Development_of_Exceptional_Talents">Nodet</a> schools
    - Publishing several short stories in Sharif Daily Magazine
    - Hosting and directing multiple episodes of podcasts and <mark>(even musical!)</mark> radio <a href="https://podcasts.google.com/feed/aHR0cHM6Ly90ZWhyYW5wb2RjYXN0LmlyL2NhdGVnb3J5L3Jhc3RhaWhhL2ZlZWQv/episode/aHR0cHM6Ly90ZWhyYW5wb2RjYXN0LmlyLz9wPTIxNzQz?sa=X&ved=0CAUQkfYCahcKEwiw6taRhbn8AhUAAAAAHQAAAAAQAQ">plays</a>
    - Designing <a href="http://computermuseum.ir">Iran's computer museum</a> exhibition and curriculum
  
#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: RoboLamb
        quote: >
          2022 -- Present (Under development) / Designer & Developer
        description: | # this will include new lines to allow paragraphs
          A 2D RPG adventure game developed with Godot that introduces teenagers to computer science and programming concepts through gameplay. Players take on the role of a hacker lamb who infiltrates an evil corp and hacks various robots and computer devices to find key information and complete different tasks.
          
          ![RoboLamb](/images/robolamb.png "robolamb")
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Intro-GD
        link: https://godotengine.org/asset-library/asset/1403
        link_text: Godot community Asset library
        additional_links:
          - title:  Github page
            icon: fab fa-github
            url: https://github.com/farhadi-erfan/intro-gd
        quote: >
          2022 / Developer
        description: | # this will include new lines to allow paragraphs
          Easy to use add--on for creating tutorials and introduction section inside godot scenes.
          
          ![Godot](/images/godot.png "godot")
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Goldoone
        link: https://drive.google.com/file/d/1gCJd__aOALFLNJTAFOp15BsaLpOo0Tal/view?usp=sharing
        link_text: download
        quote: >
          2022 / Designer & Developer
        description: | # this will include new lines to allow paragraphs
          A drag & drop 2D game developed with Godot to help elementary students improve their literacy skills through gameplay. Students play as an environmental journalist who writes reports on city events, helps out in the office, and protects a pot of flower.
          
          [![Goldoone](/images/goldoone.png 'Goldoone')](https://vimeo.com/787343192)
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Fifteen
        link: https://cafebazaar.ir/app/ir.alefedu.fifteen
        link_text: Cafe Bazaar
        quote: >
          2021 / Developer
        description: | # this will include new lines to allow paragraphs
          A simple multiplayer online game, developed with django-channels and godot, in which players had to compete to collect three cards that added up to 15, while preventing their opponent from doing so first.
          
          ![Fifteen](/images/fif.jpg 'Fifteen')
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Kamva
        link: https://kamva.academy
        link_text: Kamva
        additional_links:
          - title:  Github page
            icon: fab fa-github
            url: https://github.com/rastaiha
        quote: >
          2020 -- 2022 / CTO
        description: | # this will include new lines to allow paragraphs
          My thesis project. A gamified platform that helps institutes and teachers to hold online workshops and provide semi--personalized content to students. Empirical results shows proposed solution's effectiveness in increasing students' engagement and educational performance.

          [![Kamva](/images/kamva.png 'Kamva')](https://www.youtube.com/watch?v=5UeoLFCX45c)
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Clash of civilizations
        quote: >
          2020 (unfinished) / Designer
        description: | # this will include new lines to allow paragraphs
          A realtime online strategy game in which players took on the role of a civilization with two scores: warmongering and science. Warmongering was achieved by collecting cards and winning battles, while science was gained by solving educational quizzes, similar to the website [prodigy](https://www.prodigygame.com).

          ![Clash of civilizations](/images/cards.jpg 'Clash of civilizations')
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Kabarama dalapeste  </br> <mark><sub><sup>(Yes, I named it :D)</sup></sub></mark>
        additional_links:
          - title:  Kabaramadalapeste
            icon: fab fa-github
            url: https://github.com/Rastaiha/KabaramadalaPeste
        quote: >
          2020 / Designer
        description: | # this will include new lines to allow paragraphs
          In the early days of Covid--19, we designed an online gamified contest to promote connectivity and interaction during the transition to E--learning. Students played as pirates owning a ship, searching different islands, and solving quizzes/mysteries to find clues about golden pistachio while trading and competing with other fellow pirates.
          
          ![Kabaramadalapeste1](/images/kabar (1).png 'Kabaramadalapeste1')
          
          ![Kabaramadalapeste2](/images/kabar (2).png 'Kabaramadalapeste2')
          
          ![Kabaramadalapeste3](/images/kabar (3).png 'Kabaramadalapeste3')
      - layout: center
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Shined brightly, though...
        quote: >
          2016 -- 2019 / Director
        description: | # this will include new lines to allow paragraphs
          A 75-minute documentary based on my memories from school years and Iran's educational system.
          
          [![Shined brightly, though...](/images/shined.png 'Shined brightly, though...')](https://vimeo.com/414334902)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
